version = 1

[[annotations]]
path = "**"
SPDX-FileCopyrightText = [
    "2013-2016 anatoly techtonik <techtonik@gmail.com>",
    "2020-2025 Stephen Arnold <stephen.arnold42@gmail.com>",
]
SPDX-License-Identifier = "LGPL-2.1-or-later"
