name: Pylint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  pylint:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install tox
      run: |
        python -m pip install --upgrade pip wheel
        pip install tox tox-gh-actions
    
    - name: Run pylint
      id: pylint
      run: |
        rating=$(bash -c 'tox -e lint' | grep 'Your code has been rated at' | cut -f7 -d " ")
        echo "##[set-output name=rating;]${rating}"
        mkdir -p "${BADGE_PATH%/*}"
        echo "##[set-output name=path;]${BADGE_PATH}"
      env:
        BADGE_PATH: .github/badges/pylint-score.svg

    - name: Create pylint badge
      uses: emibcn/badge-action@v1
      with:
        label: 'Pylint score'
        status: ${{ steps.pylint.outputs.rating }}
        color: 'green'
        path: .github/badges/pylint-score.svg

    - name: Commit badges
      continue-on-error: true
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .github/badges/
        git commit -m "Update Badges"

    - name: Push badge commit
      uses: ad-m/github-push-action@master
      if: ${{ success() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: badges
        force: true
